In [22]:
import numpy as np

Массив данных 1...30 и элементы, кратные 3-м:

In [6]:
arr = np.arange(1, 31)
arr3 = arr[arr % 3 == 0]
print("Массив данных:", arr)
print("Кратные трем элементы:",arr3)

Массив данных: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
Кратные трем элементы: [ 3  6  9 12 15 18 21 24 27 30]


Матрица 6х5 -> 5х6 и сумма по столбцам:

In [13]:
m = np.arange(1, 31).reshape((6, 5))
r = m.reshape((5, 6))
print("Исходная матрица 6х5:")
print(m)
print("Сумма по столбцам: ", m.sum(axis=0))
print()
print("Измененная матрица 5х6:")
print(r)
print("Сумма по столбцам: ", r.sum(axis=0))


Исходная матрица 6х5:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
Сумма по столбцам:  [ 81  87  93  99 105]

Измененная матрица 5х6:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
Сумма по столбцам:  [65 70 75 80 85 90]


Два случайных массива, их поэлементное умножение и среднее:

In [32]:
a = np.random.rand(10)
b = np.random.rand(10)
print("Массив a: ", a)
print("Массив b: ", b)
m = a * b
print("Результат поэлементного умножения: ", m)
a = np.mean(m)
print("Среднее значение: ", a)

Массив a:  [0.13515807 0.36020862 0.56070257 0.42378665 0.32522712 0.16737798
 0.77335239 0.48103224 0.02410722 0.54176036]
Массив b:  [0.5298956  0.01678829 0.78233557 0.10827632 0.88527411 0.89180986
 0.82105748 0.94032217 0.01689245 0.89339754]
Результат поэлементного умножения:  [7.16196659e-02 6.04728637e-03 4.38657562e-01 4.58860586e-02
 2.87915151e-01 1.49269334e-01 6.34966763e-01 4.52325278e-01
 4.07230025e-04 4.84007370e-01]
Среднее значение:  0.25711016985878654
